server:
  module-config: "respip validator iterator"

  interface: 0.0.0.0
  port: 53

  # Allow common internal container network and local ranges.
  access-control: 10.0.0.0/8 allow
  access-control: 127.0.0.0/8 allow
  access-control: 172.16.0.0/12 allow
  access-control: 192.168.0.0/16 allow

  # Root files for recursive resolution and DNSSEC validation.
  auto-trust-anchor-file: "/var/lib/unbound/root.key"
  root-hints: "/etc/unbound/root.hints"

  # Security & Privacy
  hide-identity: yes
  hide-version: yes

  # Performance
  infra-keep-probing: yes
  msg-cache-size: 128m
  num-threads: 2
  outgoing-num-tcp: 32
  prefetch-key: yes
  prefetch: yes
  rrset-cache-size: 256m
  serve-expired: yes

  # Disable internal chroot and uid switch.
  chroot: ""
  username: ""

  # Logging
  log-time-ascii: yes
  logfile: ""

remote-control:
  control-enable: yes
  control-interface: /run/unbound/control.sock

rpz:
  name: "hagezi-ndr"
  zonefile: "/etc/unbound/rpz/ndr.txt"

rpz:
  name: "hagezi-pro"
  zonefile: "/etc/unbound/rpz/pro.txt"

rpz:
  name: "hagezi-tif"
  zonefile: "/etc/unbound/rpz/tif.txt"

rpz
  name: "hegezi-tld"
  zonefile: "/etc/unbound/rpz/tld.txt"

